.pullapprove.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md

- Add the pullapprove configuration file.
- Add the standard Code of Conduct and contributing docs.

Bootstrap repo

---

jenkins/config.xml
jenkins/jobs/kata-containers-agent-centos-7-4-PR/config.xml
jenkins/jobs/kata-containers-agent-centos-7-4-master/config.xml
jenkins/jobs/kata-containers-proxy-centos-7-4-PR/config.xml
jenkins/jobs/kata-containers-proxy-centos-7-4-master/config.xml
jenkins/jobs/kata-containers-runtime-centos-7-4-PR/config.xml
jenkins/jobs/kata-containers-runtime-centos-7-4-master/config.xml
jenkins/jobs/kata-containers-shim-centos-7-4-PR/config.xml
jenkins/jobs/kata-containers-shim-centos-7-4-master/config.xml
jenkins/jobs/kata-containers-tests-centos-7-4-PR/config.xml
jenkins/jobs/kata-containers-tests-centos-7-4-master/config.xml

This will add CentOS jobs for Jenkins.
Fixes #13

ci: Add CentOS jobs for Jenkins.

---

jenkins/config.xml
jenkins/jobs/kata-containers-crio-PR/config.xml
jenkins/jobs/kata-containers-packaging-ubuntu-16-04-PR/config.xml
jenkins/jobs/kata-containers-runtime-density-PR/config.xml
jenkins/jobs/kata-containers-runtime-density-master/config.xml

This PR contains three commits.
- Update main configuration that removes hardcoded golang installation
and changes the azure region that we use for the CI from WestUS2 to EastUs.
- Adds packaging job, to test changes from packaging repository
- Adds kata density jobs that report memory of kata-containers components.

Update jenkins configuration

---

jenkins/jobs/kata-containers-osbuilder-centos-7-4-PR/config.xml
jenkins/jobs/kata-containers-osbuilder-centos-7-4-master/config.xml
jenkins/jobs/kata-containers-osbuilder-fedora-27-PR/config.xml
jenkins/jobs/kata-containers-osbuilder-fedora-27-master/config.xml
jenkins/jobs/kata-containers-osbuilder-ubuntu-16-04-PR/config.xml
jenkins/jobs/kata-containers-osbuilder-ubuntu-16-04-master/config.xml

Thes are the jobs that will test the pull request and
master branch of the osbuilder repository.
Fixes #28
Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>

jenkins: Add osbuilder jobs

---

VMs/metrics/2_build_baseimage.sh
VMs/metrics/ubuntu16.04/user-data
VMs/metrics/ubuntu16.04/user-data.proxy

A short series of small fixes, including:
- fix some .gitconfig file issues
- add YAML sanity checking to try to prevent such issues in the future
- fix the USER homedir perms
- remove the auto updater package
Fixes a number of issues (noted in the relevant commits)

VMs: fix .gitconfig, sanity check YAML, fix USER perms

---

jenkins/jobs/kata-containers-agent-ubuntu-16-04-PR-initrd/config.xml
jenkins/jobs/kata-containers-agent-ubuntu-16-04-master-initrd/config.xml
jenkins/jobs/kata-containers-proxy-ubuntu-16-04-PR-initrd/config.xml
jenkins/jobs/kata-containers-proxy-ubuntu-16-04-master-initrd/config.xml
jenkins/jobs/kata-containers-runtime-ubuntu-16-04-PR-initrd/config.xml
jenkins/jobs/kata-containers-runtime-ubuntu-16-04-master-initrd/config.xml
jenkins/jobs/kata-containers-shim-ubuntu-16-04-PR-initrd/config.xml
jenkins/jobs/kata-containers-shim-ubuntu-16-04-master-initrd/config.xml
jenkins/jobs/kata-containers-tests-ubuntu-16-04-PR-initrd/config.xml
jenkins/jobs/kata-containers-tests-ubuntu-16-04-master-initrd/config.xml

We should create Jenkins nodes running initrd in ubuntu 16.04
in all our different repositories.
Fixes #47

ci: Add jenkins jobs for initrd

---

jenkins/jobs/kata-containers-agent-ubuntu-18-04-PR/config.xml
jenkins/jobs/kata-containers-agent-ubuntu-18-04-master/config.xml
jenkins/jobs/kata-containers-proxy-ubuntu-18-04-PR/config.xml
jenkins/jobs/kata-containers-proxy-ubuntu-18-04-master/config.xml
jenkins/jobs/kata-containers-runtime-ubuntu-18-04-PR/config.xml
jenkins/jobs/kata-containers-runtime-ubuntu-18-04-master/config.xml
jenkins/jobs/kata-containers-shim-ubuntu-18-04-PR/config.xml
jenkins/jobs/kata-containers-shim-ubuntu-18-04-master/config.xml
jenkins/jobs/kata-containers-tests-ubuntu-18-04-PR/config.xml
jenkins/jobs/kata-containers-tests-ubuntu-18-04-master/config.xml

Add the config.xml for the jenkins jobs for ubuntu 18.04.
Fixes #21

jenkins: Add ubuntu 18.04 jenkins jobs

---

jenkins/jobs/kata-containers-agent-opensuse-15-PR/config.xml
jenkins/jobs/kata-containers-agent-opensuse-15-master/config.xml
jenkins/jobs/kata-containers-proxy-opensuse-15-PR/config.xml
jenkins/jobs/kata-containers-proxy-opensuse-15-master/config.xml
jenkins/jobs/kata-containers-runtime-opensuse-15-PR/config.xml
jenkins/jobs/kata-containers-runtime-opensuse-15-master/config.xml
jenkins/jobs/kata-containers-shim-opensuse-15-PR/config.xml
jenkins/jobs/kata-containers-shim-opensuse-15-master/config.xml
jenkins/jobs/kata-containers-tests-opensuse-15-PR/config.xml
jenkins/jobs/kata-containers-tests-opensuse-15-master/config.xml

This will add the jenkins config for openSUSE Leap 15.
Fixes #5

jenkins: Add Jenkins jobs for openSUSE Leap

---

jenkins/jobs/kata-containers-osbuilder-centos-7-4-firecracker-PR/config.xml
jenkins/jobs/kata-containers-osbuilder-centos-7-4-firecracker-master/config.xml

This add the config for jenkins jobs for firecracker for osbuilder
repository.
Fixes #133

jenkins: Jenkis jobs for FC for osbuilder

---

jenkins/jobs/kata-containers-packaging-ubuntu-18-04-snap-PR/config.xml

Add jenkins job for snap for the packaging repository.
Fixes #140

jenkins: Add jenkins job for snap

---

jenkins/jobs/kata-containers-agent-sles-12-PR/config.xml
jenkins/jobs/kata-containers-agent-sles-12-master/config.xml
jenkins/jobs/kata-containers-proxy-sles-12-PR/config.xml
jenkins/jobs/kata-containers-proxy-sles-12-master/config.xml
jenkins/jobs/kata-containers-runtime-sles-12-PR/config.xml
jenkins/jobs/kata-containers-runtime-sles-12-master/config.xml
jenkins/jobs/kata-containers-shim-sles-12-PR/config.xml
jenkins/jobs/kata-containers-shim-sles-12-master/config.xml
jenkins/jobs/kata-containers-tests-sles-12-PR/config.xml
jenkins/jobs/kata-containers-tests-sles-12-master/config.xml

This adds the configs for the jenkins jobs for SLES.
Fixes #126

jenkins: Add jenkins jobs for SLES

---

VMs/metrics/README.md

Resolve issues with markdown.
Fixes #147.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

docs: Fix markdown

---

jenkins/jobs/kata-containers-proxy-s390x-18.04-PR-initrd/config.xml

This adds the config for s390 for the proxy repository.
Fixes #150

jenkins: Add jenkins job for s390

---

README.md

Updated top-level README to add links to all remaining docs in this repo.
Also added a Table of Contents.
Fixes: #160.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

docs: Added missing doc links

---

jenkins/jobs/kata-containers-documentation-opensuse-15-PR/config.xml

This add an openSUSE slave for the documentation repository.
Fixes #162

ci: Add jenkins job for opensuse documentation

---

Jenkins_setup.md

Last week, I have added two new ARM CI nodes in the Kata Community.
Here, based on the instructions via emails from @grahamwhaley and @chavafg and my own experience, I'd like to write a tutorial on How to set up a bare metal Jenkins Slave node. ;)
Fixes: #166
Signed-off-by: Penny Zheng <penny.zheng@arm.com>

slave_node: how to set up a bare metal jenkins slave node

---

VMs/metrics/README.md
deployment/packet/README.md

Correct spelling mistakes and formatting issues.
Fixes: #174.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

docs: Fix typos and formatting

---

jenkins/jobs/nemu-nightly-x86_64/config.xml

This add the config.xml for the new jenkins job for the nightly nemu
cache job.
Fixes #190

jenkins: Add nemu-cache jenkins job

---

jenkins/jobs/kata-containers-agent-debian-10-PR/config.xml
jenkins/jobs/kata-containers-proxy-debian-10-PR/config.xml
jenkins/jobs/kata-containers-runtime-debian-10-PR/config.xml
jenkins/jobs/kata-containers-shim-debian-10-PR/config.xml
jenkins/jobs/kata-containers-tests-debian-10-PR/config.xml

This adds the configs for the jenkins jobs for Debian 10.
Fixes #87

jenkins: Add jenkins jobs for Debian 10

---

jenkins/jobs/kata-containers-rust-agent-ubuntu-18-04-PR/config.xml

This adds the config.xml for the rust agent jenkins job.
Fixes #234

jenkins: Add rust agent jenkins job

---

jenkins/jobs/kata-containers-agent-fedora-31-PR/config.xml
jenkins/jobs/kata-containers-documentation-fedora-31-PR/config.xml
jenkins/jobs/kata-containers-osbuilder-fedora-31-PR/config.xml
jenkins/jobs/kata-containers-proxy-fedora-31-PR/config.xml
jenkins/jobs/kata-containers-runtime-fedora-31-PR/config.xml
jenkins/jobs/kata-containers-tests-fedora-31-PR/config.xml

This PR adds the config.xmls for the Fedora 31 jenkins jobs.
Fixes #238

jenkins: Add fedora 31 jobs

---

jenkins/jobs/kata-containers-agent-sles-15-PR/config.xml
jenkins/jobs/kata-containers-proxy-sles-15-PR/config.xml
jenkins/jobs/kata-containers-runtime-sles-15-PR/config.xml
jenkins/jobs/kata-containers-shim-sles-15-PR/config.xml
jenkins/jobs/kata-containers-tests-sles-15-PR/config.xml

This PR updates the SLES CI jenkins jobs from SLES 12 SP1 to SLES 15 SP1.
Fixes #264

jobs: Update SLES CI jenkins jobs

---

jenkins/jobs/kata-containers-agent-centos-8-PR/config.xml
jenkins/jobs/kata-containers-proxy-centos-8-PR/config.xml
jenkins/jobs/kata-containers-runtime-centos-8-PR/config.xml
jenkins/jobs/kata-containers-shim-centos-8-PR/config.xml
jenkins/jobs/kata-containers-tests-centos-8-PR/config.xml

We updated the CentOS CI from 7.4 to 8.0 version, this PR updates
the config.xmls.
Fixes #283

jenkins: Update jenkins jobs for CentOS

---

jenkins/jobs/kata-containers-agent-rhel-8-q35-PR/config.xml
jenkins/jobs/kata-containers-proxy-rhel-8-q35-PR/config.xml
jenkins/jobs/kata-containers-runtime-rhel-8-q35-PR/config.xml
jenkins/jobs/kata-containers-shim-rhel-8-q35-PR/config.xml
jenkins/jobs/kata-containers-tests-rhel-8-q35-PR/config.xml

We have moved from RHEL 7 to RHEL 8, this PR updates the config.xml files
from the jenkins jobs.
Fixes #285

jenkins: RHEL 8 jenkins jobs

---

jenkins/jobs/kata-containers-runtime-podman-clh-fedora-31-PR/config.xml
jenkins/jobs/kata-containers-runtime-podman-clh-fedora-31-master/config.xml
jenkins/jobs/kata-containers-tests-podman-clh-fedora-31-PR/config.xml

This adds the jenkins xmls config for podman with CLH CI.
Fixes #295

jenkins: Add jenkins jobs for podman with CLH

---

jenkins/jobs/kata-metrics-runtime-ubuntu-virtiofs-18-04-PR/config.xml
jenkins/jobs/kata-metrics-tests-ubuntu-virtiofs-18-04-PR/config.xml

This PR adds the config.xmls for the jenkins jobs for the metrics virtiofs.
Fixes #312

jenkins: Add metrics virtiofs CI jobs

---

jenkins/jobs/kata-containers-2.0-tests-ubuntu-PR-clh-containerd-k8s-minimal/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-PR-clh-containerd-k8s-minimal/config.xml

This PR add the jenkins config.xml for the clh containerd k8s
minimal tests for kata 2.0
Fixes #334

jenkins: Add jenkins jobs for clh containerd k8s minimal

---

jenkins/jobs/kata-containers-2.0-tests-ubuntu-PR-containerd-k8s-minimal/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-PR-containerd-k8s-minimal/config.xml

This PR adds the config.xml for the e2e k8s minimal containerd job
that runs in Ubuntu for kata 2.0
Fixes #341

jenkins: Add e2e minimal k8s containerd job

---

jenkins/jobs/kata-containers-2.0-ubuntu-PR-clh-containerd-k8s-full/config.xml

This PR adds the config.xml for the jenkins job for clh containerd
k8s e2e complete.
Fixes #355

jenkins: Add clh containerd k8s e2e job full

---

jenkins/jobs/kata-containers-2.0-Power9-containerd-k8s-ubuntu-20-04-PR/config.xml
jenkins/jobs/kata-containers-2.0-Power9-crio-k8s-ubuntu-20-04-PR/config.xml

Jobs CRI_CONTAINERD_K8S and CRIO_K8S on Ubuntu 20.04.
Fixes #385
Signed-off-by: MatthieuSarter <matthieu.sarter@ibm.com>

ci: add jenkins jobs for Kata 2.0 on Power 9

---

jenkins/jobs/kata-containers-2.0-centos-PR/config.xml
jenkins/jobs/kata-containers-2.0-clh-crio-ubuntu-PR/config.xml
jenkins/jobs/kata-containers-2.0-debian-PR/config.xml
jenkins/jobs/kata-containers-2.0-fedora-PR-crio-k8s-e2e-minimal/config.xml
jenkins/jobs/kata-containers-2.0-fedora-PR/config.xml
jenkins/jobs/kata-containers-2.0-firecracker-ubuntu-PR/config.xml
jenkins/jobs/kata-containers-2.0-metrics-ubuntu-20-04-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-centos-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-clh-crio-ubuntu-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-debian-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-fedora-PR-crio-k8s-e2e-minimal/config.xml
jenkins/jobs/kata-containers-2.0-tests-fedora-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-metrics-ubuntu-20-04-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-ubuntu-ARM-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-ubuntu-PR-clh-containerd-k8s-minimal/config.xml
jenkins/jobs/kata-containers-2.0-tests-ubuntu-PR-containerd-k8s-minimal/config.xml
jenkins/jobs/kata-containers-2.0-tests-ubuntu-initrd-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-ubuntu-s390x-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-ubuntu20.04-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-vfio-PR/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-20.04-PR/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-ARM-PR/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-PR-clh-containerd-k8s-minimal/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-PR-containerd-k8s-minimal/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-PR/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-initrd-PR/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-s390x-PR/config.xml
jenkins/jobs/kata-containers-2.0-vfio-PR/config.xml
jenkins/jobs/kata-containers-crio-PR/config.xml
jenkins/jobs/kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-containerd/config.xml

This PR updates the config.xmls for the jenkins jobs.
Fixes #394

jenkins: Update jenkins jobs config

---

jenkins/backup.xml
jenkins/config.xml
jenkins/io.jenkins.plugins.casc.CasCGlobalConfig.xml
jenkins/io.jenkins.plugins.junit.storage.JunitTestResultStorageConfiguration.xml
jenkins/jenkins.fingerprints.GlobalFingerprintConfiguration.xml
jenkins/jenkins.model.GlobalBuildDiscarderConfiguration.xml
jenkins/jenkins.plugins.jclouds.blobstore.BlobStorePublisher.xml
jenkins/jenkins.tasks.filters.EnvVarsFilterGlobalConfiguration.xml
jenkins/org.jenkinsci.plugins.github_branch_source.GitHubConfiguration.xml
jenkins/org.jenkinsci.plugins.resourcedisposer.AsyncResourceDisposer.xml

This PR updates and adds missing configuration jenkings files.
Fixes #399

jenkins: Update config xml files

---

jenkins/jobs/kata-containers-2-crio-PR/config.xml
jenkins/jobs/kata-containers-2.0-firecracker-jailer-ubuntu-PR/config.xml
jenkins/jobs/kata-containers-2.0-kernel-experimental-x86_64-nightly/config.xml
jenkins/jobs/kata-containers-2.0-kernel-vanilla-x86_64-nightly/config.xml
jenkins/jobs/kata-containers-2.0-pmem-ubuntu-20.04-PR/config.xml
jenkins/jobs/kata-containers-2.0-qemu-x86_64/config.xml
jenkins/jobs/kata-containers-2.0-tests-pmem-ubuntu-20.04-PR/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-PR-qemu-experimental/config.xml

This PR add the missing jenkins jobs for kata 2.0 and their config xmls.
Fixes #401

jenkins: Add missing jenkins jobs

---

jenkins/config.xml
jenkins/envInject.xml
jenkins/envinject-plugin-configuration.xml
jenkins/hudson.plugins.copyartifact.CopyArtifactConfiguration.xml
jenkins/javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration.xml
jenkins/jenkins.security.UpdateSiteWarningsConfiguration.xml
jenkins/org.jenkinsci.plugins.resourcedisposer.AsyncResourceDisposer.xml

This PR updates the jenkins configuration files. This is a periodic sync with the jenkins config files into git.
Fixes #409

jenkins: Update configuration files

---

jenkins/jobs/kata-containers-2.0-ubuntu-20.04-CONTAINERD-main-baseline/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-20.04-METRICS-main-baseline/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-20.04-PMEM-main-baseline/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-20.04-QAT-main-baseline/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-20.04-VFIO-main-baseline/config.xml

This PR adds some missing jenkins jobs that currently we are supporting.
Fixes #411

jenkins: Add jenkins jobs

---

jenkins/jobs/kata-containers-2.0-clh-tdx-x86_64/config.xml
jenkins/jobs/kata-containers-2.0-kernel-tdx-x86_64-nightly/config.xml
jenkins/jobs/kata-containers-2.0-metrics-ubuntu-20-04-PR/config.xml
jenkins/jobs/kata-containers-2.0-pmem-ubuntu-20.04-PR/config.xml
jenkins/jobs/kata-containers-2.0-qat-ubuntu-20.04-PR/config.xml
jenkins/jobs/kata-containers-2.0-qemu-tdx-x86_64/config.xml
jenkins/jobs/kata-containers-2.0-tests-metrics-ubuntu-20-04-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-qat-ubuntu-20.04-PR/config.xml
jenkins/jobs/kata-containers-2.0-vfio-PR/config.xml

This PR adds and updates some jenkins jobs that we currently
have in our kata 2.0 CI.
Fixes #443

jenkins: Add and update jenkins jobs for kata 2.0

---

VMs/metrics/README.md
deployment/packet/README.md

This PRU udpdate the url links for some README documentation.
Fixes #464

docs: Update url links for READMEs

---

.gitignore
Always_green_CI.md
README.md

Added a document for the always green CI initiative.
Fixes #417

doc: Add "Always Green CI" document

---

jobs-builder/jobs/cc.yaml

Add new flags to run k8s tests
Fixes #471
Signed-off-by: Megan Wright <megan.wright@ibm.com>
Co-authored-by: Georgina Kinge <georgina.kinge@ibm.com>

jobs-builder: Add flags for kubernetes jobs

---

jenkins/github-plugin-configuration.xml
jenkins/hudson.maven.MavenModuleSet.xml
jenkins/hudson.plugins.ansicolor.AnsiColorBuildWrapper.xml
jenkins/hudson.plugins.copyartifact.CopyArtifactConfiguration.xml
jenkins/hudson.plugins.copyartifact.TriggeredBuildSelector.xml
jenkins/hudson.plugins.copyartifact.monitor.LegacyJobConfigMigrationMonitor.xml
jenkins/hudson.plugins.emailext.ExtendedEmailPublisher.xml
jenkins/hudson.plugins.git.GitSCM.xml
jenkins/hudson.plugins.groovy.Groovy.xml
jenkins/hudson.plugins.timestamper.TimestamperConfig.xml
jenkins/hudson.scm.SubversionSCM.xml
jenkins/hudson.tasks.Mailer.xml

This PR updates some general jenkins configs.
Fixes #479

jenkins: Part 2 update jenkins configs

---

jenkins/io.jenkins.plugins.casc.CasCGlobalConfig.xml
jenkins/io.jenkins.plugins.junit.storage.JunitTestResultStorageConfiguration.xml
jenkins/javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration.xml
jenkins/jenkins.plugins.jclouds.blobstore.BlobStorePublisher.xml
jenkins/jenkins.security.UpdateSiteWarningsConfiguration.xml
jenkins/org.codefirst.SimpleThemeDecorator.xml
jenkins/org.jenkins.plugins.lockableresources.LockableResourcesManager.xml
jenkins/org.jenkinsci.plugins.conditionalbuildstep.singlestep.SingleConditionalBuilder.xml
jenkins/org.jenkinsci.plugins.docker.workflow.declarative.GlobalConfig.xml
jenkins/org.jenkinsci.plugins.ghprb.GhprbTrigger.xml
jenkins/org.jenkinsci.plugins.github_branch_source.GitHubConfiguration.xml
jenkins/org.jenkinsci.plugins.resourcedisposer.AsyncResourceDisposer.xml
jenkins/org.jenkinsci.plugins.workflow.flow.GlobalDefaultFlowDurabilityLevel.xml
jenkins/org.jenkinsci.plugins.workflow.libs.GlobalLibraries.xml

This PR updates general jenkins configuration files as the
version of Jenkins has been updated.
Fixes #481

jenkins: Update general jenkins configuration files

---

jenkins/jobs/kata-containers-2.0-tests-ubuntu-22.04-PR/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-20.04-DRAGONBALL-main-baseline/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-22.04-CONTAINERD-main-baseline/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-22.04-PR/config.xml
jenkins/jobs/kata-containers-dragonball-tests-ubuntu-20.04-PR/config.xml
jenkins/jobs/kata-containers-dragonball-ubuntu-20.04-PR/config.xml

This PR adds some missing jenkins jobs.
Fixes #448

ci: Add missing jenkins jobs

---

.github/workflows/main.yml
.github/workflows/publish_jobs.yml
jobs-builder/jobs/cc.yaml

This add the following jobs which are triggered on pull requests for
confidential-containers/operator:
confidential-containers-operator-main-ubuntu-20.04_sev-x86_64-containerd_kata-qemu-sev-PR
Fixes #495

jobs-builder: add operator CI jobs for AMD SEV

---

jenkins/config.xml
jenkins/hudson.plugins.git.GitSCM.xml
jenkins/hudson.scm.SubversionSCM.xml

This PR is to backup general jenkins configs.
Fixes #501

ci: Backup jenkins configs part 1

---

jenkins/io.jenkins.plugins.junit.storage.JunitTestResultStorageConfiguration.xml
jenkins/org.jenkinsci.plugins.ghprb.GhprbTrigger.xml
jenkins/org.jenkinsci.plugins.resourcedisposer.AsyncResourceDisposer.xml

This PR updates some general jenkins configs xmls.
Fixes #503

jenkins: Update general jenkins configs

---

jenkins/jobs/kata-containers-2.0-clh-cc-x86_64/config.xml
jenkins/jobs/kata-containers-2.0-kernel-cc-x86_64/config.xml
jenkins/jobs/kata-containers-2.0-qemu-cc-x86_64/config.xml
jenkins/jobs/kata-containers-2.0-virtiofsd-cc-x86_64/config.xml

This PR adds missing config xmls jobs.
Fixes #505

jenkins: Add missing jobs

---

jenkins/jobs/image-nightly-x86_64/config.xml
jenkins/jobs/kata-containers-2-tests-crio-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-metrics-ubuntu-20-04-PR/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-1804-PR-cloud-hypervisor-k8s-containerd/config.xml
jenkins/jobs/metrics-2.0-reboot-ubuntu-worker/config.xml

This PR backup some general jenkins configs.
Fixes #507

jenkins: Backup jenkins configs

---

jenkins/jobs/kata-containers-2.0-qemu-s390x/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-s390x-main-PR/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-s390x-snap-PR/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-s390x-unit-PR/config.xml

This PR adds the missing jenkins job config for qemu s390x.
Fixes #517

jenkins: Add missing jenkins job config

---

jobs-builder/jobs/cc.yaml
jobs-builder/jobs/include/os2node.yaml.inc

Adding SNP job to the job builder so that #5594 in tests can run.
Fixes: #5593

job-builder: Add SNP job
