kata-containers/ci

VMs/metrics/ubuntu16.04/user-data
VMs/metrics/ubuntu16.04/user-data.proxy

The apt-daily[-upgrade] services are invoked at boot.
They are suspects in taking the apt-lock, which causes
the CI scripts to fail (during apt operations, as the
lock is already then held). Disable them permanently by
masking them off.
Fixes: #50

metrics: VMs: disable apt-daily services

---

VMs/metrics/6_start_clone_agent.sh
VMs/metrics/README.md
VMs/metrics/jenkins_start.sh
VMs/metrics/jenkins_stop.sh

There were some useful details we did not have in the README, such as prereqs and
how to set up the user on the slave machine.
Also add a couple of jenkins helper scripts for launching from the jenkins SSH slave plugin.

VMs: metrics: update README and add helper scripts

---

VMs/metrics/2_build_baseimage.sh
VMs/metrics/ubuntu16.04/user-data

Some of our metrics tests use `perf` to gather data. Enable that both at the VM level
and with the tooling inside the VM.

VMs: metrics: enable perf inside VM

---

.gitignore
deployment/packet/README.md
deployment/packet/create_packet.yaml
deployment/packet/delete_packet.yaml
deployment/packet/env.yaml
deployment/packet/install_packet.yaml

Add a set of Ansible scripts to make packet.net machine deployment
easier and repeatable for Kata CI machines.

deployment: packet.net ansible scripts

---

deployment/packet/install_packet.yaml

Perf package should be added so we can run the cpu network tests. We
also need to remove the unattended-upgrades.
Fixes #81

metrics: Add perf and disable unattended-upgrades to Ansible

---

deployment/packet/install_packet.yaml

Our scripts use `killall` sometimes during the cleanup
phase - add it via the `psmisc` package.
Fixes: #90

deployment: packet: add killall via psmisc package

---

deployment/packet/README.md
deployment/packet/add_checkmetrics.yaml

For a metrics slave to correctly run, it requires a correctly
named checkmetrics.toml file placed in the right directory.
Add an ansible helper script to copy this file over.
Fixes: #88

deployment: packet: add script to copy over checkmetrics

---

README.md

Add a link out to the CI status page so it can be more easily found.
Fixes: #107

README: Add link to CI status page

---

jenkins/jobs/kata-containers-agent-ubuntu-16-04-PR-firecracker/config.xml
jenkins/jobs/kata-containers-agent-ubuntu-16-04-master-firecracker/config.xml
jenkins/jobs/kata-containers-proxy-ubuntu-16-04-PR-firecracker/config.xml
jenkins/jobs/kata-containers-proxy-ubuntu-16-4-master-firecracker/config.xml
jenkins/jobs/kata-containers-runtime-ubuntu-16-04-PR-firecracker/config.xml
jenkins/jobs/kata-containers-runtime-ubuntu-16-04-master-firecracker/config.xml
jenkins/jobs/kata-containers-shim-ubuntu-16-04-PR-firecracker/config.xml
jenkins/jobs/kata-containers-shim-ubuntu-16-04-master-firecracker/config.xml
jenkins/jobs/kata-containers-tests-ubuntu-16-04-PR-firecracker/config.xml
jenkins/jobs/kata-containers-tests-ubuntu-16-04-master-firecracker/config.xml

Add jenkins jobs for Firecracker for the different kata repositories.
Fixes #105

jenkins: Add Firecracker jobs

---

deployment/packet/install_packet.yaml

We don't want anything sporadically running in the background
on the machine in case they disrupt our test results.
Disable all the timers present in the default install.
Fixes: #121

packet.net: disable background timers

---

jenkins/jobs/kata-containers-agent-ubuntu-nemu/config.xml
jenkins/jobs/kata-containers-proxy-ubuntu-nemu/config.xml
jenkins/jobs/kata-containers-runtime-ubuntu-nemu/config.xml
jenkins/jobs/kata-containers-shim-ubuntu-nemu/config.xml
jenkins/jobs/kata-containers-tests-ubuntu-nemu/config.xml

Nemu jobs for agent, proxy, runtime, shim and tests
repositories.
Fixes: #130.
Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>

jobs: Add nemu jobs for the different kata repos

---

README.md

There was no link out to the CI control phrase wiki page. Add one.
Fixes: #195

docs: Add a link to the control phrase wiki

---

.ci/lib.sh
.ci/run.sh
.ci/setup.sh
.ci/static-checks.sh
.travis.yml

Add a basic set of CI scripts so that static analysis checks are performed on PRs in this repo.
Also, add a Travis configuration file. Note that language is set to `go` so that `golang` will be installed automatically (since it is required by the `.ci/*` scripts).
Fixes: #197.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

Add CI scripts

---

jenkins/jobs/kata-containers-osbuilder-ARM-18.04-PR/config.xml
jenkins/jobs/kata-containers-runtime-Power8-ubuntu-16-04-PR-initrd/config.xml

Currently, we are missing the xmls for the jobs of osbuilder ARM
and Power 8 runtime. This adds the missing config.xmls
Fixes #199

ci: Add jenkins jobs for ARM and Power8

---

jenkins/jobs/kata-containers-agent-ubuntu-1804-PR-firecracker/config.xml
jenkins/jobs/kata-containers-firecracker-PR/config.xml
jenkins/jobs/kata-containers-osbuilder-ubuntu-1804-firecracker-PR/config.xml
jenkins/jobs/kata-containers-proxy-ubuntu-1804-PR-firecracker/config.xml
jenkins/jobs/kata-containers-runtime-ubuntu-1804-PR-firecracker/config.xml
jenkins/jobs/kata-containers-shim-ubuntu-1804-PR-firecracker/config.xml
jenkins/jobs/kata-containers-tests-ubuntu-1804-PR-firecracker/config.xml

We update the Firecracker CI to use Ubuntu instead of CentOS. This updates
the configs for the Firecracker jenkins jobs.
Fixes #201

ci: Update Firecracker jenkins jobs

---

jenkins/jobs/kata-containers-tests-ubuntu-18-04-master-ksm-pentest-popular-images/config.xml

This adds the config.xml for the jenkins job that runs the KSM test,
the pentesting and the docker popular images tests.
Fixes #209

jenkins: Add jenkins job for KSM, pentesting, and popular docker images

---

jenkins/jobs/kernel-nightly-x86_64/config.xml
jenkins/jobs/nemu-nightly-x86_64/config.xml
jenkins/jobs/qemu-nightly-x86_64/config.xml

This adds the qemu cache jenkins job config as well as updates the
nemu, image and kernel cache jenkins jobs.
Fixes #214

ci: Add and update jenkins jobs for the cache jobs

---

jenkins/jobs/kernel-experimental-nightly-x86_64/config.xml
jenkins/jobs/qemu-experimental-nightly-x86_64/config.xml

This adds the config.xmls for the jenkins jobs for qemu and kernel cache
experimental.
Fixes #223

jenkins: Add jenkins jobs for cache qemu and kernel experimental

---

jenkins/jobs/cloud-hypervisor-nightly-x86_64/config.xml
jenkins/jobs/kata-containers-runtime-podman-fedora-31-PR/config.xml
jenkins/jobs/kata-containers-tests-podman-fedora-31-PR/config.xml

This adds the configs for the podman and cloud hypervisor cache jenkins
jobs.
Fixes #247

jenkins: Add jenkins jobs for podman and clh

---

jenkins/jobs/kata-containers-agent-rhel-7-q35-PR/config.xml
jenkins/jobs/kata-containers-proxy-rhel-7-q35-PR/config.xml
jenkins/jobs/kata-containers-runtime-rhel-7-q35-PR/config.xml
jenkins/jobs/kata-containers-shim-rhel-7-q35-PR/config.xml
jenkins/jobs/kata-containers-tests-rhel-7-q35-PR/config.xml

We have changed the RHEL jenkins jobs to use MACHINE TYPE=q35, this PR
reflects those changes.
Fixes #278

jenkins: Update RHEL jenkins jobs

---

jenkins/jobs/kata-containers-agent-fedora-32-PR/config.xml
jenkins/jobs/kata-containers-proxy-fedora-32-PR/config.xml
jenkins/jobs/kata-containers-runtime-fedora-32-PR/config.xml
jenkins/jobs/kata-containers-shim-fedora-32-PR/config.xml
jenkins/jobs/kata-containers-tests-fedora-32-PR/config.xml

Now that we have been enabled fedora ci from 31 to 32, this PR
updates the jenkins jobs config.xmls.
Fixes #288

jenkins: Update Fedora jobs from 31 to 32

---

jenkins/jobs/kata-metrics-runtime-ubuntu-clh-18-04-PR/config.xml
jenkins/jobs/kata-metrics-tests-ubuntu-clh-18-04-PR/config.xml

This PR adds the config.xmls files for the metrics CLH.
Fixes #304

jenkins: Add jenkins jobs for metrics CLH CI

---

jenkins/jobs/kata-containers-2.0-centos-PR/config.xml
jenkins/jobs/kata-containers-2.0-debian-PR/config.xml
jenkins/jobs/kata-containers-2.0-fedora-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-centos-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-debian-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-fedora-PR/config.xml

This PR adds the jenkins jobs configs for Debian, Centos and Fedora
for the kata 2.0 CI.
Fixes #306

jenkins: Add jobs for Debian, Centos and Fedora for 2.0 CI

---

jenkins/jobs/kata-containers-agent-ubuntu-18-04-virtiofs-PR/config.xml
jenkins/jobs/kata-containers-proxy-ubuntu-18-04-virtiofs-PR/config.xml
jenkins/jobs/kata-containers-runtime-ubuntu-18-04-virtiofs-PR/config.xml
jenkins/jobs/kata-containers-shim-ubuntu-18-04-virtiofs-PR/config.xml
jenkins/jobs/kata-containers-tests-ubuntu-18-04-virtiofs-PR/config.xml

Now that we enabled the conformance posix tests for virtiofs with the following
flag TEST_CONFORMANCE=true, we also need to update the jenkins jobs to reflect
that change.
Fixes #309

jenkins: Update virtiofs jobs with conformance tests

---

jenkins/jobs/kata-containers-2.0-runtime-ubuntu-PR-containerd-k8s-minimal/config.xml
jenkins/jobs/kata-containers-2.0-tests-ubuntu-PR-containerd-k8s-minimal/config.xml

This PR add the config.xmls for the k8s minimal containerd job
for kata 2.0 which will execute a small amount of e2e k8s tests.
Fixes #316

ci: Add k8s minimal jobs for kata 2.0

---

jenkins/config.xml

Currently we try to install a specific version of containers, from the
EL7 version of docker-ce.repo, while running an EL8 machine, which ends
up causing conflicts such as:
```
Error:
Problem: package podman-1.9.3-2.module+el8.2.1+6867+366c07d6.x86_64 requires runc >= 1.0.0-57, but none of the providers can be installed
- package containerd.io-1.2.6-3.3.el7.x86_64 conflicts with containerd provided by containerd.io-1.3.7-3.1.el8.x86_64
- package containerd.io-1.3.7-3.1.el8.x86_64 conflicts with runc provided by containerd.io-1.2.6-3.3.el7.x86_64
- package containerd.io-1.3.7-3.1.el8.x86_64 conflicts with containerd provided by containerd.io-1.2.6-3.3.el7.x86_64
- cannot install both containerd.io-1.3.7-3.1.el8.x86_64 and containerd.io-1.2.6-3.3.el7.x86_64
```
In order to avoid such issue, …

config,el8: Avoid conflicts when installing containerd

---

jenkins/jobs/kata-containers-2.0-centos-PR/config.xml
jenkins/jobs/kata-containers-2.0-fedora-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-centos-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-fedora-PR/config.xml

This PR adds the configs for the CentOS and Fedora jenkins jobs for
the kata 2.0 CI
Fixes #332

jenkins: Add CentOS and Fedora jobs for kata 2.0

---

jenkins/jobs/kata-containers-2.0-tests-ubuntu-PR/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-PR/config.xml

This PR adds the config.xml for the jenkins jobs that we have
for the ubuntu CI in kata 2.0
Fixes #336

jenkins: Add jenkins jobs for ubuntu in kata 2.0

---

jenkins/jobs/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/config.xml

This PR adds the missing jenkins config.xml for the ubuntu clh virtiofs
for kata 2.0
Fixes #338

ci: Add jenkins job for clh virtiofs for kata 2.0

---

jenkins/jobs/kata-containers-2.0-firecracker-ubuntu-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-firecracker-ubuntu-P/config.xml

This PR adds the configs for the jenkins jobs for firecracker for
kata 2.0
Fixes #371

jenkins: Add jenkins jobs for firecraker in kata 2.0

---

jenkins/jobs/kata-containers-2.0-tests-clh-crio-ubuntu-PR/config.xml

This PR adds the config for the clh+crio jenkins job in for kata 2.0
Fixes #373

jenkins: Add jenkins job for clh+crio in kata 2.0

---

jenkins/jobs/kata-containers-2.0-metrics-ubuntu-20-04-PR/config.xml
jenkins/jobs/kata-containers-2.0-tests-metrics-ubuntu-20-04-PR/config.xml

This PR adds the metrics CI configs for kata 2.0
Fixes #375

jenkins: Add metrics CI jobs for kata 2.0

---

jenkins/jobs/kata-containers-2.0-tests-ubuntu20.04-PR/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-20.04-PR/config.xml

This PR adds the config files for the ubuntu 20.04 CI.
Fixes #379

jenkins: Add jenkins jobs for kata 2.0 for ubuntu 20.04

---

jenkins/jobs/kata-containers-2.0-ubuntu-s390x-PR/config.xml

An s390x job existed back in the v1 days, but it's long gone. Start with
a fresh s390x v2 CI, Ubuntu 20.04, image, containerd, already exists at
http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-s390x-PR
Fixes #387
Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>
/cc @chavafg @GabyCT @fidencio

jenkins: Add basic s390x job

---

jenkins/jobs/kata-containers-2.0-tests-ubuntu-s390x-PR/config.xml

following #388; Ubuntu 20.04, image, containerd, already running at
http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-s390x-PR/
Fixes: #390
Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>

jenkins: Add s390x tests job

---

jenkins/jobs/kata-containers-2.0-tests-ubuntu-s390x-PR/config.xml
jenkins/jobs/kata-containers-2.0-ubuntu-s390x-PR/config.xml

like we do in the main job, on ARM, and on Power, because the s390x test
instance does not quite have the disk space to keep tons of failed
tests. The list of branches was not edited by me.
Fixes: #392
Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>

jenkins: Clean up workspace in s390x tests job

---

.gitignore
README.md
jobs-builder/README.md
jobs-builder/jjb.conf.template
jobs-builder/jobs/dependencies.yaml
jobs-builder/jobs/include/os2node.yaml.inc
jobs-builder/publish_jobs.sh

This introduces the files and scripts to use with Jenkins
Job Builder to manage our CI jobs.
As a proof of concept, it is generated only four jobs:
kata-containers-main-kernel-experimental-x86_64
kata-containers-main-kernel-vanilla-x86_64
kata-containers-main-qemu-x86_64
kata-containers-stable-2.2-qemu-x86_64
Fixes #343
(cherry-picked from commit a22049ce3d656b7f2574c98f4aa7b3b59511749a)

main | Introduce Jenkins Job Builder for CI

---

.github/workflows/main.yml
.github/workflows/publish_jobs.yml
.gitignore

It is added two new github workflows in this PR:
- On pull request, check that changes didn't break the jobs builder
- On push, automatically publish to Jenkins if any job configuration changed (it requires adding secrets on the configuration of this repository)
Fixes #343

github: add workflows for the jobs builder

---

jobs-builder/jobs/include/ci_entrypoint.sh.inc
jobs-builder/jobs/include/os2node.yaml.inc
jobs-builder/jobs/pr.yaml

This created the backbone to generate pull request and baseline jobs
with Jenkins Job Builder. Currently the yaml files are configured to
generate PR and baseline jobs for Fedora 35.
The following new jobs will be generated:
kata-containers-fedora-35-x86_64-CRIO_K8S-PR
kata-containers-fedora-35-x86_64-CRIO_K8S_MINIMAL-PR
kata-containers-main-fedora-35-x86_64-CRIO_K8S-baseline
kata-containers-main-fedora-35-x86_64-CRIO_K8S_MINIMAL-baseline
tests-fedora-35-x86_64-CRIO_K8S-PR
tests-fedora-35-x86_64-CRIO_K8S_MINIMAL-PR
Fixes #389

jobs-builder: add PR jobs for Fedora 35

---

jobs-builder/jjb.conf.template

It should not use HTTPS to connect to http://jenkins.katacontainers.io
Fixes #428

jobs-builder: fix url in jjb.conf.template

---

Jenkins_setup.md

This PR updates the jenkins setup documentation by updating the corresponding
kata containers repository for kata 2.0
Fixes #434

docs: Update Jenkins setup documentation

---

jobs-builder/jobs/include/os2node.yaml.inc
jobs-builder/jobs/pr.yaml

using jjb, also remove the centos8 node/label as it's not
deprecated
Baseline is passing for some time now
http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-centos-8-stream-CRIO_K8S-main-baseline/
Fixes: #440
Signed-off-by: Snir Sheriber <ssheribe@redhat.com>

ci: add CentOS 8 Straem K8S jobs

---

jenkins/jobs/kata-containers-2.0-Power9-containerd-k8s-ubuntu-20-04-PR/config.xml

The Power job has been quite stable from the baseline runs.
Allow it to be run on /test.
Fixes: #438
Signed-off-by: Amulyam24 <amulmek1@in.ibm.com>

jenkins: Enable power job to be triggered on /test

---

.github/workflows/main.yml

Adding the following changes:
* This repository hasn't any golang code so it doesn't make sense to run
the tests for many different golang versions. Also the 'Running tests' step
is bogus as the called script (github.com/kata-containers/ci/tree/main/.ci/run.sh)
just return `true`, thus it was removed.
* Allow to test on forked repos
Fixes #426

github: remove uneeded workflow steps

---

jobs-builder/jobs/cc.yaml
jobs-builder/jobs/include/cc-ci_entrypoint.sh.inc

This added the following jobs which are triggered on pull requests
targeting the CCv0 branch:
kata-containers-CCv0-ubuntu-20.04-x86_64-CC_CRI_CONTAINERD-PR
tests-CCv0-ubuntu-20.04-x86_64-CC_CRI_CONTAINERD-PR
Fixes #445
----
Note: I created this new `cc.yaml` configuration file from the `pr.yaml`. Just a few changes were required to change, mostly configurations to ensure the job watches the CCv0 branch and only run for that branch. In the future we could try to merge the CC and Kata regular jobs into a single template file.

jobs-builder: add jobs for CC_CRI_CONTAINERD

---

jobs-builder/jobs/cc.yaml

This added the following jobs which are triggered on pull requests
targeting the CCv0 branch:
kata-containers-CCv0-ubuntu-20.04-x86_64-CC_SKOPEO_CRI_CONTAINERD-PR
tests-CCv0-ubuntu-20.04-x86_64-CC_SKOPEO_CRI_CONTAINERD-PR
Fixes #451
----
*Note:* this PR depends on https://github.com/kata-containers/tests/pull/4573

jobs-builder: add jobs for CC_SKOPEO_CRI_CONTAINERD

---

jobs-builder/jobs/cc.yaml

The current tests with CC are using QEMU as the VMM.  Although right now
those are non-TEE specific, we better start testing against all the
supported VMMs sooner than later, this adding support to Cloud
Hypervisor here.
Fixes: #454
Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

CCv1 | cc: Also test with Cloud Hypervisor

---

jobs-builder/jobs/pr.yaml

This is going to disable the CentOS 8 Stream baseline job as well as
the jobs triggered on pull requests.
Fixes #458

Disable CentOS 8 Stream jobs

---

Jenkins_setup.md

This PR updates the urls for the Jenkins setup information to the
current kata 2.0 links.
Fixes #462

docs: Update urls for jenkins setup document

---

CONTRIBUTING.md

This PR updates the url link for the contribution guide.
Fixes #467

docs: Update url for contribution guide

---

jobs-builder/jobs/cc.yaml

Added a new template and project to generate pull-request jobs for the
confidential-containers/operator repository.
The following new job will be generated:
confidential-containers-operator-main-ubuntu-20.04-x86_64-containerd_kata-qemu-PR
Fixes #491

jobs-builder: add PR jobs for confidential-containers/operator

---

jobs-builder/jobs/cc.yaml
jobs-builder/jobs/include/cc-ci_entrypoint.sh.inc
jobs-builder/jobs/include/os2node.yaml.inc

This added the following jobs which are triggered on pull requests
targeting the CCv0 branch:
kata-containers-CCv0-ubuntu-20.04_sev-x86_64-CC_SEV_CRI_CONTAINERD_K8S
tests-CCv0-ubuntu-20.04_sev-x86_64-CC_SEV_CRI_CONTAINERD_K8S
Fixes #484 
Depends on https://github.com/kata-containers/tests/pull/4862

jobs-builder: add jobs for CC_SEV_CRI_CONTAINERD

---

jobs-builder/jobs/cc.yaml

Delete the workspace before the build is may be needed for jobs running on baremetal machine.

jobs-builder: delete workspace before build starts

---

jobs-builder/jobs/cc.yaml

This add the following jobs which are triggered on pull requests for confidential-containers/operator:
confidential-containers-operator-main-ubuntu-20.04-x86_64-containerd_kata-clh-PR
Fixes #497

jobs-builder: add operator CI jobs for kata-clh

---

jobs-builder/jobs/pr.yaml

Now that kata-containers 3.0.0 is about to be released, let's enable CI on the stable-2.3 branch.
Signed-off-by: Greg Kurz <groug@kaod.org>

jobs-builder: enable CI for stable-2.3 branch of kata-containers

---

jobs-builder/README.md
jobs-builder/publish_jobs.sh
jobs-builder/trash

After the jobs are published on Jenkins it might be desirable to also remove those not needed anymore or that were generated but not wanted. This added a way to delete the jobs as well.
Fixes #523

jobs-builder: add mechanism to delete jobs

---

jobs-builder/jobs/cc.yaml

Some Kata tests read the authenticated image registry token from the REGISTRY_CREDENTIAL_ENCODED environment variable so that it should be exported on the build environment of all CCv0 jobs.
Fixes #525

jobs-builder: add credential binding for the quay.io registry

---

.github/workflows/publish_jobs.yml

The publish jobs action should be executed when the jobs-builder/trash file changes.
Fixes #523

github: publish jobs if jobs-builder/trash changed

---

jobs-builder/jobs/cc.yaml

Added a new variable (tee) to the confidential containers job template so that if export it will generate a trigger phrase to allow "/test-tee".
For example, the SEV jobs will have the trigger phrase:
.*(\n|^|\s)/(re)?test(-ubuntu)?(-sev)?(\n|$|\s)+.*
Allow for triggering the job with a simple "/test-sev".
Fixes #531

jobs-builder: allow to trigger only SEV jobs

---

jobs-builder/jobs/cc.yaml

On commit e2005a9642a82c it was added a mechanism to trigger SEV jobs that actually broke all triggers of all CC jobs. The XML generated is like below (with line breaks):
```
<allowMembersOfWhitelistedOrgsAsAdmin>true</allowMembersOfWhitelistedOrgsAsAdmin>
<triggerPhrase>
.*(\n|^|\s)/(re)?test(-ubuntu)?(-sev)?(\n|$|\s)+.*
</triggerPhrase>
<skipBuildPhrase>.*\[skip\W+ci\].*</skipBuildPhrase>
<onlyTriggerPhrase>true</onlyTriggerPhrase>
```
With this fix it will generate the XML correctly, trimming line breaks and spaces.
Fixes #531

jobs-builder: fix CC jobs triggers

---

jobs-builder/jobs/include/cc-ci.groovy

The confidential-containers-ci job has a timeout to wait for the runtime-payload images to be built that is currently to small. Let's increase it to 90 minutes which is the time the images should be built on worst case.
Fixes #539

jobs-builder: increase timeout waiting images

---

jobs-builder/jobs/cc.yaml
jobs-builder/jobs/include/operator-ci_entrypoint.sh.inc

This will create jobs that run daily to "exercise" the stability of the CI jobs for Confidential Containers.
The following jobs will be generated:
- confidential-containers-operator-main-ubuntu-20.04-x86_64-containerd_kata-clh-baseline
- confidential-containers-operator-main-ubuntu-20.04-x86_64-containerd_kata-qemu-baseline
- confidential-containers-operator-main-ubuntu-20.04_sev-x86_64-containerd_kata-qemu-sev-baseline
- kata-containers-CCv0-ubuntu-20.04-x86_64-CC_CRI_CONTAINERD-baseline
- kata-containers-CCv0-ubuntu-20.04-x86_64-CC_CRI_CONTAINERD_CLOUD_HYPERVISOR-baseline
- kata-containers-CCv0-ubuntu-20.04-x86_64-CC_CRI_CONTAINERD_K8S-baseline
- kata-containers-CCv0-ubuntu-20.04_sev-x86_64-CC_SEV_CRI_CONTAINERD_K8S-baseline
Fixes #542

Add baseline jobs for Confidential Containers

---

.github/workflows/main.yml
.github/workflows/publish_jobs.yml

The recently released jenkins-job version 5.0 fail to generate our jobs due to deprecated features removed. We can either fix our yaml files or keep using a known to work version of the tool. I chose the later option as Jenkins will be replaced with Github actions soon, so let's keep it simple. The last known working version of jenkins-job is 4.3.0.
Fixes #548

github: pin the jenkins-job version
